### PR TITLE
[BigQuery] syntax debug highlight

### PR DESCRIPTION
**Pull request by MRzNone**
# Syntax Error
image

# Not found error

image

### CODE REVIEW

**Comment by MRzNone** [comment]
Monaco supports display error message when hovering over the error mark, but the react version we are using is not supporting is.  I created an [issue](https://github.com/suren-atoyan/monaco-react/issues/93) on their side.

I decided to keep the debug message below since the message display on hovering is not available.

**Comment by suren-atoyan** [comment]
I just want to inform you that the react version of the editor also supports it. The problem is there was a typo in your code, I've already sent the correct version; check it [here](https://github.com/suren-atoyan/monaco-react/issues/93).

**Comment by MRzNone** [comment]
Fixed typo.  Hovering works.  Removed dry-run error message.

# Syntax error
image


# "semantic" error
image

**Comment by cbwilkes** [comment]
Is dry-run error message still removed. I don't think we should remove the print out and force the user to hover the mouse.

**Comment by cbwilkes** [comment]
We will add back the dry run error message in a later PR

**Pull request merged**
